"""added posted time

Revision ID: e1dfd05be8f1
Revises: f2b481ebf08d
Create Date: 2019-05-30 12:16:08.581444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1dfd05be8f1'
down_revision = 'f2b481ebf08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    op.drop_column('comments', 'time_posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('time_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
